import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from './components/Layout/Navbar'
import Hero from './components/Sections/Hero'
import Events from './components/Sections/Events'
import Footer from './components/Layout/Footer'
import Featured from './components/Sections/Featured'
import VuVist from './components/Sections/VuVist'
import Impact from './components/Sections/Impact'
import Ukraine from './components/Sections/Ukraine'
import CampusTour from './components/Sections/CampusTour'
import News from './components/Sections/News'
import Vacancies from './components/Sections/Vacancies'
import Calender from './components/Sections/Calender'
import Amsterdam from './components/Sections/Amsterdam'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Events />
      <VuVist />
      <Impact />
      <Ukraine />
      <News />
      <Calender />
      <Vacancies />
      <Amsterdam />
      <CampusTour />
      <Featured />
      <Footer />
    </>
  )
}
